In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [5]:
def gradient_descent(x, y):
    m_curr = b_curr = 0
    iterations = 30
    n = len(x)
    learning_rate  = 10

    for i in range(iterations):
        y_predicted = (m_curr * x) + b_curr

        
        cost = (1/n)* sum([val**2 for val in (y-y_predicted)])
        
        md = -(2/n) * sum(x*(y-y_predicted))
        bd = -(2/n)* sum(y-y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd

        print('m: {} , b:{}, iterations: {}, cost: {}'.format(m_curr, b_curr, i, cost))

In [6]:
x = np.array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67])
y = np.array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73])

gradient_descent(x, y)

m: 98918.00000000001 , b:1398.0, iterations: 0, cost: 5199.1
m: -9367226132.000002 , b:-132179612.00000001, iterations: 1, cost: 46338603086336.71
m: 887056195012178.1 , b:12517125526378.002, iterations: 2, cost: 4.1554991212948135e+23
m: -8.400231636726116e+19 , b:-1.18534490192127e+18, iterations: 3, cost: 3.726519963262638e+33
m: 7.954838932124885e+24 , b:1.122496162197974e+23, iterations: 4, cost: 3.341825044657435e+43
m: -7.533061607419215e+29 , b:-1.0629797556027022e+28, iterations: 5, cost: 2.9968428290189686e+53
m: 7.133647540241925e+34 , b:1.0066189969047716e+33, iterations: 6, cost: 2.687473707278726e+63
m: -6.755410997605515e+39 , b:-9.532465689857329e+37, iterations: 7, cost: 2.410041279902153e+73
m: 6.397229115839092e+44 , b:9.027040261282042e+42, iterations: 8, cost: 2.1612486682572074e+83
m: -6.0580385671642e+49 , b:-8.54841323641067e+47, iterations: 9, cost: 1.9381393360337772e+93
m: 5.7368324030137775e+54 , b:8.095163724246292e+52, iterations: 10, cost: 1.7380619551338

In [7]:
test_arr = np.array([1, 2, 3, 4])
mul = 10* test_arr + 0.1
print(mul)
arr = np.array([1, 2, 3,5])
res = arr *  mul
print(res)

[10.1 20.1 30.1 40.1]
[ 10.1  40.2  90.3 200.5]


In [13]:
model = linear_model.LinearRegression()
print(len(x), len(y))
model.fit([x], [y])


10 10


LinearRegression()

In [14]:
model.coef_

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
model.intercept_

array([98., 68., 81., 80., 83., 52., 66., 30., 68., 73.])

# One Hot Encoding
