In [19]:
from sklearn.datasets import load_wine
import numpy as np
import pandas as pd

In [20]:
data = load_wine()

In [21]:
dir(data)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [23]:
df = pd.DataFrame(np.array(data.data))

In [24]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [34]:
data.target_names
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

### Df info

In [27]:
df.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [35]:
x = df
y = data.target
X_train, X_test, y_train, y_test = train_test_split(x, y)

### Gaussian NB

In [36]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [37]:
y_predicted = model.predict(X_test)
y_predicted

array([0, 2, 0, 2, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 1,
       2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 0, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0, 0,
       1])

In [40]:
y_test

array([0, 2, 0, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 1,
       2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 0, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0, 0,
       1])

In [41]:
model.score(X_test, y_test)

0.9777777777777777